### PR TITLE
Small proposal for allowing to post to any topic from outside

### PR DESCRIPTION
**Pull request by KarstenB**
Hey again,
This is a small modification that I had to make in order to be able to post to some other topic from my code (and re-use the existing client). It is a bit hacky, maybe you like it, maybe not :)

Karsten

### CODE REVIEW

**Comment by dschanoeh** [comment]
Hi Karsten,

thanks for the PR. To be honest, looking at the code again, I'm confused why I didn't make access to the method protected instead of public. Using that method, one could build a misbehaving client that causes unexpected issues. 
However - looking at other implementations of the Homie Convention - some seem to allow external access to a similar method as well.

What do you think about the following:
1. We make this method here protected so it cannot be used from the outside
2. We create a new method that allows you to publish a whole MqttMessage to wherever you want and we put a warning sign on it that you might break the convention using it

If you like the approach, could you modify the PR (and also please switch from tabs to 4 spaces to match the style)?

Cheers,
Jan

**Comment by KarstenB** [comment]
I am fine with either way. So I updated the PR to your request :)

**Comment by dschanoeh** [comment]
Looks good, thanks!

**Comment by KarstenB** [comment]
Awesome, thanks for developing the library and merging the PR :)

**Pull request merged**
